[2023-09-23 02:20:14,777] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:20:14] "[31m[1mPOST /new HTTP/1.1[0m" 422 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:22:58,999] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:22:58] "OPTIONS /new HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:22:59,005] ERROR log_exception() L1449 Exception on /new [POST] - call_trace=/usr/local/lib/python3.9/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_openapi3/scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "/usr/local/lib/python3.9/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/app/app.py", line 66, in register
    print('REGISTRO: ' + body)
TypeError: can only concatenate str (not "UserSchema") to str
[2023-09-23 02:22:59,014] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:22:59] "[35m[1mPOST /new HTTP/1.1[0m" 500 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:28:37,562] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:28:37] "OPTIONS /new HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:28:37,569] ERROR log_exception() L1449 Exception on /new [POST] - call_trace=/usr/local/lib/python3.9/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_openapi3/scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "/usr/local/lib/python3.9/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/app/app.py", line 66, in register
    print('REGISTRO: ' + body)
TypeError: can only concatenate str (not "UserSchema") to str
[2023-09-23 02:28:37,571] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:28:37] "[35m[1mPOST /new HTTP/1.1[0m" 500 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:29:11,351] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:29:11] "OPTIONS /new HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:29:11,357] ERROR log_exception() L1449 Exception on /new [POST] - call_trace=/usr/local/lib/python3.9/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_openapi3/scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "/usr/local/lib/python3.9/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/app/app.py", line 66, in register
    print('REGISTRO: ${body}')
TypeError: can only concatenate str (not "UserSchema") to str
[2023-09-23 02:29:11,375] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:29:11] "[35m[1mPOST /new HTTP/1.1[0m" 500 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:31:45,575] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:31:45] "OPTIONS /new HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:31:45,582] ERROR log_exception() L1449 Exception on /new [POST] - call_trace=/usr/local/lib/python3.9/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_openapi3/scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "/usr/local/lib/python3.9/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/app/app.py", line 66, in register
    print(f'REGISTRO: {body}')
TypeError: can only concatenate str (not "UserSchema") to str
[2023-09-23 02:31:45,605] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:31:45] "[35m[1mPOST /new HTTP/1.1[0m" 500 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:34:35,576] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:34:35] "OPTIONS /new HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:34:35,582] ERROR log_exception() L1449 Exception on /new [POST] - call_trace=/usr/local/lib/python3.9/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_openapi3/scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
  File "/usr/local/lib/python3.9/site-packages/flask_openapi3/do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
  File "/app/app.py", line 66, in register
    print('REGISTRO: ' + str(body))
TypeError: can only concatenate str (not "UserSchema") to str
[2023-09-23 02:34:35,599] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:34:35] "[35m[1mPOST /new HTTP/1.1[0m" 500 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-23 02:35:08,031] INFO _log() L224  172.23.0.1 - - [23/Sep/2023 02:35:08] "OPTIONS /new HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.9/site-packages/werkzeug/_internal.py L224 
